#!/usr/bin/env python
"""Digit Defender -> Android. Copies the game into android/app, builds the APK
in the WSL build box (Ubuntu on D:), installs and runs it on the USB phone.

    python android\\sync.py                  sync (default): refresh android/app from the game, bump VERSION
    python android\\sync.py all              sync + build + install + run + logs
    python android\\sync.py setup            one-time: create the WSL build box "dd-android" on D:\\WSL
    python android\\sync.py build            build the APK (first time 30-60 min: SDK/NDK/numpy; later a few minutes)
    python android\\sync.py clean build      rebuild the project from scratch (keeps the SDK/NDK cache)
    python android\\sync.py install run      adb install + launch on the phone
    python android\\sync.py logs             python / SDL lines from logcat  (--follow 20 = 20 s live)
    python android\\sync.py status           what is set up, connected and built

Options: --version X.Y.Z (else the patch number bumps on every sync), --no-bump,
         --serial S (adb device), --release, --follow N, --verbose (full build output;
         android/build.log always has everything).
Windows-side helper: stdlib only (pygame, present for the game, draws the icon).
"""
import argparse
import os
import re
import shutil
import subprocess
import sys
import time
import urllib.request
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent          # the game
AND = ROOT / "android"
APP = AND / "app"
WSL_DIR = Path(r"D:\WSL")
DISTRO = "dd-android"
ROOTFS_URL = ("https://cloud-images.ubuntu.com/wsl/releases/24.04/current/"
              "ubuntu-noble-wsl-amd64-wsl.rootfs.tar.gz")
ROOTFS = WSL_DIR / "ubuntu-noble-wsl-amd64.rootfs.tar.gz"
ADB = os.environ.get("ADB") or r"D:\Android\sdk\platform-tools\adb.exe"
PACKAGE = "org.johncarter.digitdefender"
ACTIVITY = "org.kivy.android.PythonActivity"
COPY_FILES = ("game.py", "settings.py")
COPY_DIRS = ("sim", "world", "render", "ui", "assets")
IGNORE = shutil.ignore_patterns("__pycache__", "*.pyc", ".pytest_cache", "tests", "saves")
MAIN_STUB = '''"""Digit Defender - Android entry (generated by android/sync.py; the code is mobile/entry.py)."""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mobile.entry import main

if __name__ == "__main__":
    sys.exit(main())
'''
INTERESTING = re.compile(r"(?i)error|exception|traceback|failed|warning: |apk|available in|"
                         r"building |downloading|unpacking|installing|need |not found|stderr|"
                         r"^\[|compiling|distribution|bootstrap")


def log(msg):
    print(f"[sync] {msg}", flush=True)


def decode(raw):
    """wsl.exe talks UTF-16 for its own messages, the Linux side UTF-8."""
    if b"\x00" in raw:
        return raw.decode("utf-16-le", "ignore").replace("\x00", "")
    return raw.decode("utf-8", "replace")


def run(cmd, check=True, capture=False, **kw):
    if capture:
        p = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, **kw)
        out = decode(p.stdout)
        if check and p.returncode:
            raise SystemExit(f"command failed ({p.returncode}): {' '.join(map(str, cmd))}\n{out}")
        return out
    p = subprocess.run(cmd, **kw)
    if check and p.returncode:
        raise SystemExit(f"command failed ({p.returncode}): {' '.join(map(str, cmd))}")
    return p.returncode


def stream(cmd, logfile=None, verbose=True):
    """Run cmd, print its output live (all of it, or the interesting lines
    plus a heartbeat) and keep everything in logfile."""
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    fh = open(logfile, "w", encoding="utf-8") if logfile else None
    n = 0
    for raw in iter(proc.stdout.readline, b""):
        line = decode(raw).rstrip("\r\n")
        n += 1
        if fh:
            fh.write(line + "\n")
            fh.flush()                                   # tail-able while the build runs
        if verbose or INTERESTING.search(line):
            print(line, flush=True)
        elif n % 250 == 0:
            print(f"[sync] ... {n} lines ({datetime.now():%H:%M:%S})", flush=True)
    proc.wait()
    if fh:
        fh.close()
    return proc.returncode


def wsl_path(p):
    p = Path(p).resolve()
    return "/mnt/" + p.drive[0].lower() + p.as_posix()[2:]


def wsl_distros():
    out = run(["wsl", "-l", "-q"], check=False, capture=True)
    return [line.strip() for line in out.splitlines() if line.strip()]


def wsl_bash(script, env=None, logfile=None, verbose=True):
    """Run android/wsl/<script> inside the build box as root (CRLF-safe).
    Parameters travel as environment assignments inside the command string:
    `wsl -- bash -c script args` silently drops positional arguments."""
    src = wsl_path(AND / "wsl" / script)
    assigns = " ".join(f"{k}='{v}'" for k, v in (env or {}).items())
    inner = f"tr -d '\\r' < '{src}' > /tmp/dd_{script} && {assigns} bash /tmp/dd_{script}"
    cmd = ["wsl", "-d", DISTRO, "-u", "root", "--", "bash", "-c", inner]
    return stream(cmd, logfile=logfile, verbose=verbose)


# ---- steps --------------------------------------------------------------------------

def read_version():
    p = AND / "VERSION"
    return p.read_text().strip() if p.exists() else "0.1.0"


def bump_version(explicit=None, bump=True):
    cur = read_version()
    if explicit:
        new = explicit
    elif bump:
        parts = cur.split(".")
        parts[-1] = str(int(re.sub(r"\D", "", parts[-1]) or 0) + 1)
        new = ".".join(parts)
    else:
        new = cur
    (AND / "VERSION").write_text(new + "\n")
    spec = AND / "buildozer.spec"
    text = spec.read_text(encoding="utf-8")
    text, n = re.subn(r"(?m)^version = .*$", f"version = {new}", text)
    if n != 1:
        raise SystemExit("buildozer.spec has no 'version = ' line")
    spec.write_text(text, encoding="utf-8")
    return new


def git_stamp():
    try:
        rev = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, capture_output=True,
                             text=True, timeout=10).stdout.strip() or "nogit"
        dirty = subprocess.run(["git", "status", "--porcelain", "--", ".", ":!android/app"], cwd=ROOT,
                               capture_output=True, text=True, timeout=10).stdout.strip()
        return rev + ("+" if dirty else "")
    except Exception:
        return "nogit"


def make_art(force=False):
    """icon.png (512) and presplash.png (1280x720) drawn with pygame, once."""
    icon, splash = AND / "icon.png", AND / "presplash.png"
    if icon.exists() and splash.exists() and not force:
        return
    os.environ.setdefault("SDL_VIDEODRIVER", "dummy")
    import pygame
    pygame.font.init()
    big = pygame.font.SysFont("consolas", 340, bold=True)
    s = pygame.Surface((512, 512), pygame.SRCALPHA)
    pygame.draw.rect(s, (30, 62, 30), (0, 0, 512, 512), border_radius=96)
    for i in range(8):                                     # a faint checker
        for j in range(8):
            if (i + j) % 2:
                pygame.draw.rect(s, (36, 72, 36), (i * 64, j * 64, 64, 64))
    pygame.draw.rect(s, (90, 120, 90), (0, 0, 512, 512), 18, border_radius=96)
    for i in range(6):                                     # a wall line
        pygame.draw.rect(s, (110, 110, 110), (58 + i * 68, 398, 60, 52), border_radius=8)
        pygame.draw.rect(s, (70, 70, 70), (58 + i * 68, 398, 60, 52), 3, border_radius=8)
    t = big.render("7", True, (255, 215, 0))
    s.blit(t, ((512 - t.get_width()) // 2, 30))
    pygame.image.save(s, str(icon))
    p = pygame.Surface((1280, 720))
    p.fill((12, 24, 12))
    title = pygame.font.SysFont("consolas", 96, bold=True).render("DIGIT DEFENDER", True, (255, 220, 90))
    p.blit(title, ((1280 - title.get_width()) // 2, 260))
    tag = pygame.font.SysFont("consolas", 30, bold=True).render("mine digits, build math, defend the HQ",
                                                                True, (140, 160, 140))
    p.blit(tag, ((1280 - tag.get_width()) // 2, 380))
    pygame.image.save(p, str(splash))
    log(f"drew {icon.name} and {splash.name}")


def step_sync(args):
    version = bump_version(args.version, bump=not args.no_bump)
    if APP.exists():
        shutil.rmtree(APP)
    APP.mkdir(parents=True)
    for name in COPY_FILES:
        shutil.copy2(ROOT / name, APP / name)
    for name in COPY_DIRS:
        shutil.copytree(ROOT / name, APP / name, ignore=IGNORE)
    shutil.copytree(AND / "mobile", APP / "mobile", ignore=IGNORE)
    (APP / "main.py").write_text(MAIN_STUB, encoding="utf-8")
    stamp = git_stamp()
    (APP / "mobile" / "build_info.py").write_text(
        f'VERSION = "{version}"\nCOMMIT = "{stamp}"\nBUILT = "{datetime.now():%Y-%m-%d %H:%M}"\n',
        encoding="utf-8")
    make_art()
    n = sum(1 for p in APP.rglob("*") if p.is_file())
    log(f"android/app refreshed: {n} files, version {version} ({stamp})")
    return version


def step_setup(args):
    if DISTRO in wsl_distros():
        log(f"WSL distro {DISTRO} exists")
    else:
        WSL_DIR.mkdir(parents=True, exist_ok=True)
        if not ROOTFS.exists():
            log(f"downloading Ubuntu 24.04 rootfs (~360 MB) to {ROOTFS}")
            urllib.request.urlretrieve(ROOTFS_URL, ROOTFS)
        log(f"importing {DISTRO} into {WSL_DIR / DISTRO}")
        run(["wsl", "--import", DISTRO, str(WSL_DIR / DISTRO), str(ROOTFS), "--version", "2"])
    log("installing the buildozer toolchain (a few minutes the first time)")
    rc = wsl_bash("setup.sh", verbose=True)
    if rc:
        raise SystemExit(f"setup failed ({rc})")


def step_build(args):
    if DISTRO not in wsl_distros():
        raise SystemExit(f"no WSL distro {DISTRO}: run  python android\\sync.py setup  first")
    if not APP.exists():
        step_sync(args)
    mode = "release" if args.release else "debug"
    t0 = time.time()
    log(f"buildozer android {mode} in {DISTRO} (log: android/build.log)")
    rc = wsl_bash("build.sh", {"DD_SRC": wsl_path(AND), "DD_MODE": mode},
                  logfile=AND / "build.log", verbose=args.verbose)
    mins = (time.time() - t0) / 60
    if rc:
        raise SystemExit(f"build failed ({rc}) after {mins:.1f} min - see android/build.log")
    apk = newest_apk()
    log(f"built in {mins:.1f} min: {apk} ({apk.stat().st_size / 1e6:.1f} MB)" if apk else "no APK produced?")


def step_clean(args):
    rc = wsl_bash("build.sh", {"DD_SRC": wsl_path(AND), "DD_MODE": "clean"})
    if rc:
        raise SystemExit(f"clean failed ({rc})")


def newest_apk():
    apks = sorted((AND / "bin").glob("*.apk"), key=lambda p: p.stat().st_mtime) if (AND / "bin").exists() else []
    return apks[-1] if apks else None


def adb(*a, serial=None, check=True, capture=True, **kw):
    cmd = [ADB] + (["-s", serial] if serial else []) + list(a)
    return run(cmd, check=check, capture=capture, **kw)


def device_state(serial=None):
    out = adb("devices", serial=None, check=False)
    rows = [l.split() for l in out.splitlines()[1:] if l.strip()]
    if serial:
        rows = [r for r in rows if r[0] == serial]
    if not rows:
        return None, "no device (plug the phone in, USB debugging on)"
    return rows[0][0], rows[0][1]


def step_install(args):
    apk = newest_apk()
    if apk is None:
        raise SystemExit("no APK in android/bin: run  python android\\sync.py build")
    serial, state = device_state(args.serial)
    if state != "device":
        raise SystemExit(f"phone not ready: {state} (accept the USB debugging prompt on the phone, then retry)")
    log(f"installing {apk.name} on {serial}")
    out = adb("install", "-r", "-d", str(apk), serial=serial)
    print(out.strip())
    if "Success" not in out:
        raise SystemExit("adb install did not report Success")


def step_run(args):
    serial, state = device_state(args.serial)
    if state != "device":
        raise SystemExit(f"phone not ready: {state}")
    adb("shell", "am", "force-stop", PACKAGE, serial=serial, check=False)
    adb("logcat", "-c", serial=serial, check=False)
    out = adb("shell", "am", "start", "-n", f"{PACKAGE}/{ACTIVITY}", serial=serial)
    print(out.strip())
    log("launched; give it ~10 s, then  python android\\sync.py logs")


LOG_TAGS = ["python:V", "PythonActivity:V", "SDL:V", "SDL/APP:V", "AndroidRuntime:E", "DEBUG:V", "libc:F"]


def step_logs(args):
    serial, state = device_state(args.serial)
    if state != "device":
        raise SystemExit(f"phone not ready: {state}")
    cmd = [ADB, "-s", serial, "logcat", "-v", "time", "-s", *LOG_TAGS]
    if args.follow:
        log(f"following logcat for {args.follow} s")
        try:
            p = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=args.follow)
            out = p.stdout
        except subprocess.TimeoutExpired as exc:
            out = exc.stdout or b""
    else:
        out = subprocess.run(cmd + ["-d"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT).stdout
    text = decode(out)
    lines = text.splitlines()
    print("\n".join(lines[-400:]))
    if "Traceback" in text:
        log("a Python traceback is in the log above")


def step_status(args):
    serial, state = device_state(args.serial)
    print(f"phone        : {serial or '-'} {state}")
    have = DISTRO in wsl_distros()
    print(f"WSL build box: {'present' if have else 'missing (run setup)'} ({DISTRO} at {WSL_DIR / DISTRO})")
    if have:
        rc = subprocess.run(["wsl", "-d", DISTRO, "-u", "root", "--", "test", "-f", "/root/.dd-setup-done"]).returncode
        print(f"toolchain    : {'installed' if rc == 0 else 'not installed (run setup)'}")
    apk = newest_apk()
    print(f"VERSION      : {read_version()}   app/: {'synced' if APP.exists() else 'not synced'}")
    print(f"latest APK   : {apk.name + f'  ({apk.stat().st_size / 1e6:.1f} MB, {datetime.fromtimestamp(apk.stat().st_mtime):%Y-%m-%d %H:%M})' if apk else '-'}")


STEPS = {"sync": step_sync, "setup": step_setup, "build": step_build, "clean": step_clean,
         "install": step_install, "run": step_run, "logs": step_logs, "status": step_status}


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("steps", nargs="*", default=["sync"], help="sync setup build clean install run logs status all")
    p.add_argument("--version", default=None, help="set android/VERSION (else the patch number bumps on sync)")
    p.add_argument("--no-bump", action="store_true", help="keep the current VERSION on sync")
    p.add_argument("--serial", default=None, help="adb device serial")
    p.add_argument("--release", action="store_true", help="buildozer android release (unsigned) instead of debug")
    p.add_argument("--follow", type=int, default=0, help="logs: follow logcat for N seconds")
    p.add_argument("--verbose", action="store_true", help="build: print every buildozer line")
    args = p.parse_args(argv)
    steps = []
    for s in args.steps:
        if s == "all":
            steps += ["sync", "build", "install", "run", "logs"]
        elif s in STEPS:
            steps.append(s)
        else:
            p.error(f"unknown step {s!r}")
    for s in steps:
        if s == "logs" and "run" in steps and not args.follow:
            time.sleep(10)                                   # let the app start before dumping the log
        STEPS[s](args)
    return 0


if __name__ == "__main__":
    sys.exit(main())
